### ISSUE TITLE
Improve styles & markup 

### ISSUE THREAD

**Issue by ivan-kleshnin** [ivan-kleshnin/cyclejs-examples#1]
Need more accurate layouts with minal investments.

**Comment by ivan-kleshnin** [comment]
Checked the surface. The only flexbox framework which looks _production ready_ is http://ink.sapo.pt
Most are abandoned for years... And **ink** is SASS only. So only **Bootstrap** for now...

**Comment by scabbiaza** [comment]
What do you say if we will include bootstrap from cdn?
1. We can get rid of whole bower in this case.
2. When I started explored this repo I was checking index.html and saw all examples without bootstrap styles, because I didn't install from bower. I think I will be not alone in this scenario.
3. Currently bower is installing bootstrap, semantic and jquery (Bs dep). Would be good do not have this files in project.
4. I don't think we will need to customize Bs in the future for this project

**Comment by ivan-kleshnin** [comment]
I wanted to create stable offline version. I need to add mention about `$ npm install` + `$ bower install`
Question about Bootstrap / Semantic is in progress.

**Comment by ivan-kleshnin** [comment]
No longer relevant.
