### ISSUE TITLE
Some code conventions

### ISSUE THREAD

**Issue by staltz** [ivan-kleshnin/cyclejs-examples#2]
Hi, first of all, I have to say I really like this repo. It's taking shape as a really good reference of examples.

In the code I noticed the tendency to write

``` javascript
let DOM = Cycle.createDOMUser("main");
DOM.inject(View).inject(Model).inject(Intent).inject(DOM);
```

But I think it's very harmful for framework learners the name "DOM", since the actual meaning of this variable is really "user". I recommend calling it "domUser" or just "user". The idea is that the actual user is a DataFlowNode (input is the view, output is the interaction events). That's what a real human does with a user interface: it sees it (view) and it interacts with it (events).

**Comment by ivan-kleshnin** [comment]
Thank you! I actually wanted to ask you about that `User` but you've already answered.
I changed that varname because `User` sticks strongly in my head as base class for user roles. 
`User > Admin`, `User > Client` etc. Perphaps it's my backend legacy experience.

I never thought about it from the point you described, but it makes sense to me now. 
I will update this to be `User`. That reasoning is worth to be mentioned in the docs somewhere.
I tried to come with less polysemantic word but it's hard. `Intent` is a very neat one.
