### ISSUE TITLE
routing 2.2

### ISSUE THREAD

**Issue by hesidoryn** [ivan-kleshnin/cyclejs-examples#20]
I'm a beginner in cyclejs, so sorry for maybe dumb questions. And my english)
I'm searching routing solutions. Encore i'm looking for answer on question: "Can i create spa with cyclejs".
I tried to use cyclic-router, everything is working, but page is always refreshing on click link. I.e. as i think it's not spa approach. 
Later i found your repository and examples in routing. I thought that I found what I was looking for. But i found one detail: when i refresh page in "some_link" in app, server gives me "Cannot GET /some_link". 
Can you explain me why it causes and tell how to create spa using cyclejs?

**Comment by ivan-kleshnin** [comment]
> I tried to use cyclic-router, everything is working, but page is always refreshing on click link. I.e. as i think it's not spa approach. 

If page refreshes at click – it basically means click is not intercepted and default browser behavior is applied. Different routers provide different techniques and APIs to enable this interception but it should be there in one way or another.

> But i found one detail: when i refresh page in "some_link" in app, server gives me "Cannot GET /some_link". 

This is intentional and correct. I put this link to demo that links which are not declared in router are not intercepted (we need an option to redirect to external site or another app). 
As this demo has no backend – nothing intercepts that click and you see your default browser message for HTTP 404 response.

> Can you explain me how to create spa using cyclejs?

I believe key elements of most SPAs are covered here. 
Unfortunately I don't have enough time a.t.m to create and support extended examples.

**Comment by hesidoryn** [comment]
Thanks for answer. 

> But i found one detail: when i refresh page in "some_link" in app, server gives me "Cannot GET /some_link".

I meant that when i refresh localhost:8080/about or something declared in router link my browser gives me "Cannot GET /about" whatever. Why it causes?

**Comment by ivan-kleshnin** [comment]
> I meant that when i refresh localhost:8080/about or something declared in router link my browser gives me "Cannot GET /about" whatever. Why it causes?

We serve `public` folder.
There is only `public/index.html` so the only possible entry point is `/`. 

**After page load, JS is used to control stuff but with direct access (or refresh) there is no JS because the page itself is missing.**

"Workarounds" (in quotes because it's not a bug): 

1) add `public/about.html` or `public/about/index.html` etc. pages with the same content as `index.html`. Drawback: DRY violations
2) add backend part with appropriate routing stuff

My goal in this project was to present frontend part of the scheme.
You would get the same behavior with React / Backbone / etc.
Nothing specific to CycleJS here.
